version: "2.1"

services:
  motioneye:
    build: motioneye
    privileged: true
    # network_mode: host
    ports:
      # motioneye web interface
      - "80:80"
      # motion control http interface
      - "7999:7999"
      # camera streaming endpoints, add others as needed
      - "8081-8090:8081-8090"
    volumes:
      - etc:/etc/motioneye
      - media:/var/lib/motioneye
      - run:/var/run/motion
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'

volumes:
  etc:
  media:
  run:
      